package com.beszel.android.ui.theme

import androidx.compose.ui.graphics.Color

// Teal seed palette — light
val TealPrimary = Color(0xFF006A60)
val TealOnPrimary = Color(0xFFFFFFFF)
val TealPrimaryContainer = Color(0xFF9FF2E3)
val TealOnPrimaryContainer = Color(0xFF00201C)

// Teal seed palette — dark
val TealPrimaryDark = Color(0xFF83D5C6)
val TealOnPrimaryDark = Color(0xFF003731)
val TealPrimaryContainerDark = Color(0xFF005048)
val TealOnPrimaryContainerDark = Color(0xFF9FF2E3)

// Blue accent
val BluePrimary = Color(0xFF0061A4)
val BluePrimaryContainer = Color(0xFFD1E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BluePrimaryDark = Color(0xFFA1C9FF)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFFD1E4FF)

// Purple accent
val PurplePrimary = Color(0xFF6B4EA0)
val PurplePrimaryContainer = Color(0xFFEBDDFF)
val PurpleOnPrimaryContainer = Color(0xFF250059)
val PurplePrimaryDark = Color(0xFFD2BCFF)
val PurplePrimaryContainerDark = Color(0xFF523686)
val PurpleOnPrimaryContainerDark = Color(0xFFEBDDFF)

// Rose accent
val RosePrimary = Color(0xFFB3261E)
val RosePrimaryContainer = Color(0xFFFFDAD5)
val RoseOnPrimaryContainer = Color(0xFF410001)
val RosePrimaryDark = Color(0xFFFFB4A8)
val RosePrimaryContainerDark = Color(0xFF930009)
val RoseOnPrimaryContainerDark = Color(0xFFFFDAD5)

// Amber accent
val AmberPrimary = Color(0xFF7A5800)
val AmberPrimaryContainer = Color(0xFFFFDEA0)
val AmberOnPrimaryContainer = Color(0xFF261900)
val AmberPrimaryDark = Color(0xFFF7BD47)
val AmberPrimaryContainerDark = Color(0xFF5C4200)
val AmberOnPrimaryContainerDark = Color(0xFFFFDEA0)

// Shared semantic colors — light
val Secondary = Color(0xFF4A635F)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFCDE8E1)
val OnSecondaryContainer = Color(0xFF06201C)
val Tertiary = Color(0xFF456179)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFCCE5FF)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val WarningLight = Color(0xFFA3631F)
val WarningContainerLight = Color(0xFFFFDDB5)
val OnWarningContainerLight = Color(0xFF2B1700)
val SuccessLight = Color(0xFF1F6E34)
val SuccessContainerLight = Color(0xFFA4F1AD)
val OnSuccessContainerLight = Color(0xFF002107)
val BackgroundLight = Color(0xFFF4FBF8)
val OnBackgroundLight = Color(0xFF171D1B)
val SurfaceLight = Color(0xFFF4FBF8)
val OnSurfaceLight = Color(0xFF171D1B)
val SurfaceDimLight = Color(0xFFD5DBD8)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEEF5F1)
val SurfaceContainerLight2 = Color(0xFFE8EFEC)
val SurfaceContainerHighLight = Color(0xFFE3EAE6)
val SurfaceContainerHighestLight = Color(0xFFDDE4E1)
val OnSurfaceVariantLight = Color(0xFF3F4946)
val OutlineLight = Color(0xFF6F7975)
val OutlineVariantLight = Color(0xFFBEC9C5)
val InverseSurfaceLight = Color(0xFF2B3230)
val InverseOnSurfaceLight = Color(0xFFECF2EF)
val InversePrimaryLight = Color(0xFF83D5C6)

// Shared semantic colors — dark
val SecondaryDark = Color(0xFFB1CCC5)
val OnSecondaryDark = Color(0xFF1C3531)
val SecondaryContainerDark = Color(0xFF324B48)
val OnSecondaryContainerDark = Color(0xFFCDE8E1)
val TertiaryDark = Color(0xFFACC9E6)
val OnTertiaryDark = Color(0xFF143349)
val TertiaryContainerDark = Color(0xFF2D4A61)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val WarningDark = Color(0xFFFFB86B)
val WarningContainerDark = Color(0xFF7C4A00)
val OnWarningContainerDark = Color(0xFFFFDDB5)
val SuccessDark = Color(0xFF88D894)
val SuccessContainerDark = Color(0xFF00531B)
val OnSuccessContainerDark = Color(0xFFA4F1AD)
val BackgroundDark = Color(0xFF0E1513)
val OnBackgroundDark = Color(0xFFDDE4E1)
val SurfaceDark = Color(0xFF0E1513)
val OnSurfaceDark = Color(0xFFDDE4E1)
val SurfaceDimDark = Color(0xFF0E1513)
val SurfaceContainerLowestDark = Color(0xFF09100E)
val SurfaceContainerLowDark = Color(0xFF171D1B)
val SurfaceContainerDark2 = Color(0xFF1B211F)
val SurfaceContainerHighDark = Color(0xFF252B29)
val SurfaceContainerHighestDark = Color(0xFF303634)
val OnSurfaceVariantDark = Color(0xFFBEC9C5)
val OutlineDark = Color(0xFF89938F)
val OutlineVariantDark = Color(0xFF3F4946)
val InverseSurfaceDark = Color(0xFFDDE4E1)
val InverseOnSurfaceDark = Color(0xFF2B3230)
val InversePrimaryDark = Color(0xFF006A60)
